=== openxava/openxava/openxava/src/main/resources/xava/dtds/editors.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT editors (editor*)>

<!ELEMENT editor (property*, formatter?, list-formatter?, (for-type | for-stereotype | for-model-property | for-valid-values | for-references | for-reference | for-collections | for-element-collections | for-descriptions-lists | for-collection | for-tabs | for-tab | for-annotation)*)>
<!ATTLIST editor
 name CDATA #IMPLIED
 url CDATA #REQUIRED
 format (true|false) "true" 
 depends-stereotypes CDATA #IMPLIED
 depends-properties CDATA #IMPLIED
 frame (true|false) "false"
 always-reload (true|false) "false"
 composite (true|false) "false" 
 icon CDATA #IMPLIED
 init-action CDATA #IMPLIED
 release-action CDATA #IMPLIED
 selectable-items (true|false) "true"
 default-label-format (normal|small|no-label) #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
  name CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT formatter (set*)>
<!ATTLIST formatter
  class CDATA #IMPLIED
	from-type (true|false) "false"
>

<!ELEMENT list-formatter (set*)>
<!ATTLIST list-formatter
  class CDATA #IMPLIED
	from-type (true|false) "false"
>

<!ELEMENT set EMPTY>
<!ATTLIST set
 property CDATA #REQUIRED
 value CDATA #REQUIRED 
>

<!ELEMENT for-type EMPTY>
<!ATTLIST for-type
 type CDATA #REQUIRED
>

<!ELEMENT for-stereotype EMPTY>
<!ATTLIST for-stereotype
 stereotype CDATA #REQUIRED
>

<!ELEMENT for-model-property EMPTY>
<!ATTLIST for-model-property
 model CDATA #REQUIRED
 property CDATA #REQUIRED 
>

<!ELEMENT for-valid-values EMPTY>

<!ELEMENT for-references EMPTY>

<!ELEMENT for-reference EMPTY>
<!ATTLIST for-reference
 model CDATA #REQUIRED
>

<!ELEMENT for-collections EMPTY>

<!ELEMENT for-element-collections EMPTY>

<!ELEMENT for-descriptions-lists EMPTY>

<!ELEMENT for-collection EMPTY>
<!ATTLIST for-collection
 model CDATA #REQUIRED
>

<!ELEMENT for-tabs (has-type*, has-annotation*, has-stereotype*)>

<!ELEMENT has-type EMPTY>
<!ATTLIST has-type
  type CDATA #IMPLIED
>

<!ELEMENT has-annotation EMPTY>
<!ATTLIST has-annotation
  annotation CDATA #IMPLIED
>

<!ELEMENT has-stereotype EMPTY>
<!ATTLIST has-stereotype
  stereotype CDATA #IMPLIED
>


<!ELEMENT for-tab EMPTY>
<!ATTLIST for-tab
 model CDATA #REQUIRED
>

<!ELEMENT for-annotation EMPTY>
<!ATTLIST for-annotation
 annotation CDATA #REQUIRED
>

=== openxava/openxava/openxava/src/main/resources/xava/default-editors.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE editors SYSTEM "dtds/editors.dtd">

<!--
	In your project use the name 'editors.xml' or 'editores.xml'
	
	Instead of modifying this file it's better to create your own editors.xml 
	(or editores.xml) in your project to override this default value
	for your application.	
-->

<editors>
  
	<editor name="List" url="listEditor.jsp" icon="table-large"
		init-action="List.init"
		release-action="List.release"> 
		<for-tabs/>
	</editor>
	
	<editor name="Charts" url="chartsEditor.jsp"
		selectable-items="false" 
		icon="chart-line" 
		init-action="Chart.init" 
		release-action="Chart.release"> 
		<for-tabs/>
	</editor>	
	
	<editor name="Cards" url="cardsEditor.jsp" 
		icon="view-module" 
		selectable-items="false"> 
		<for-tabs/>
	</editor>	
	
	<editor name="Calendar" url="calendarEditor.jsp" 
		icon="calendar" 
		selectable-items="false"> 
		<for-tabs>
			<has-type type="java.time.LocalDate" />
			<has-type type="java.util.Date" />
			<has-type type="java.sql.Date" />
			<has-type type="java.sql.Timestamp" />
			<has-type type="java.time.LocalDateTime" />
			<has-annotation annotation="DateTime"/>
			<has-stereotype stereotype="DATETIME"/>
			<has-stereotype stereotype="FECHAHORA"/>
		</for-tabs>
	</editor>
		
	<editor name="Reference" url="referenceEditor.jsp" frame="true" composite="true">
		<for-references/>
	</editor>
		
	<editor name="Collection" url="collectionEditor.jsp">
		<for-collections/>
	</editor>
	
	<editor name="ElementCollection" url="elementCollectionEditor.jsp">
		<for-element-collections/>
	</editor>

	<editor name="DescriptionsList" url="descriptionsEditor.jsp">
		<for-descriptions-lists/>
	</editor>
	
	<editor name="CollectionChart" url="collectionChartEditor.jsp">
	    <for-annotation annotation="org.openxava.annotations.Chart"/>
	</editor>	
		
	<editor name="TextField" url="textEditor.jsp">
		<list-formatter class="org.openxava.formatters.HTMLFilterListFormatter" />
		<for-type type="java.lang.String" />
	</editor>	


	<editor name="NumericField" url="textEditor.jsp">
		<for-type type="java.math.BigDecimal" />
		<for-type type="java.math.BigInteger" />
		<for-type type="int" />
		<for-type type="java.lang.Integer" />
		<for-type type="long" />
		<for-type type="java.lang.Long" />
		<for-type type="short" /> 
		<for-type type="java.lang.Short" />
		<for-type type="double" /> 
		<for-type type="java.lang.Double" />
		<for-type type="float" /> 
		<for-type type="java.lang.Float" />						
	</editor>		
 
	<editor name="BooleanCheckBox" url="booleanEditor.jsp">
		<formatter class="org.openxava.formatters.BooleanFormatter" >
			<set property="nullAsFalse" value="true"/>
		</formatter>
		<list-formatter class="org.openxava.formatters.BooleanListFormatter" />
		<for-type type="boolean" />
		<for-type type="java.lang.Boolean" />
	</editor>
	
	<editor name="BooleanYesNoCombo" url="booleanYesNoEditor.jsp">
		<formatter class="org.openxava.formatters.BooleanFormatter" />
		<list-formatter class="org.openxava.formatters.BooleanListFormatter" />
		<for-model-property model="MyReportColumn" property="booleanValue" />
	</editor>	

	<editor name="DateCalendar" url="dateCalendarEditor.jsp">
		<formatter class="org.openxava.formatters.DateFormatter" />
		<for-type type="java.util.Date" />
	</editor>
	
	<editor name="LocalDateCalendar" url="dateCalendarEditor.jsp">
		<formatter class="org.openxava.formatters.LocalDateFormatter" />
		<for-type type="java.time.LocalDate" />
	</editor>
	
	<editor name="LocalTimeCalendar" url="timeCalendarEditor.jsp">
		<formatter class="org.openxava.formatters.TimeFormatter"/>
		<for-type type="java.time.LocalTime" />
	</editor>
	
	<editor name="LocalDateTimeCalendar" url="dateTimeCombinedCalendarEditor.jsp">
		<formatter class="org.openxava.formatters.LocalDateTimeFormatter"/>
		<for-type type="java.time.LocalDateTime" />
	</editor>

	<editor name="ValidValuesCombo" url="validValuesEditor.jsp">
		<for-valid-values />
	</editor>

	<editor name="ValidValuesRadioButton" url="radioButtonEditor.jsp">
		<property name="horizontal" value="true" />
	</editor>
	<editor name="ValidValuesVerticalRadioButton"
		url="radioButtonEditor.jsp">
		<property name="horizontal" value="false" />
	</editor>
	<editor name="ValidValuesHorizontalRadioButton"
		url="radioButtonEditor.jsp">
		<property name="horizontal" value="true" />
	</editor>

	<editor name="Enum" url="validValuesEditor.jsp">
		<list-formatter class="org.openxava.formatters.EnumListFormatter"/>
		<for-type type="java.lang.Enum" />
	</editor>

	<editor name="StringTime" url="textEditor.jsp">
		<formatter class="org.openxava.formatters.StringTimeFormatter" />
		<for-stereotype stereotype="HORA" />
		<for-stereotype stereotype="TIME" />
		<for-annotation annotation="org.openxava.annotations.StringTime"/> 
	</editor>

	<editor name="Timestamp" url="textEditor.jsp">
		<formatter class="org.openxava.formatters.SQLTimeFormatter" />
		<for-type type="java.sql.Time" />
	</editor>
	
	<editor name="Password" url="passwordEditor.jsp"> 
		<for-stereotype stereotype="PASSWORD" /> 
		<for-stereotype stereotype="CONTRASENA" />
		<for-annotation annotation="org.openxava.annotations.Password"/> 
	</editor>

	<editor name="Money" url="moneyEditor.jsp"> 
		<formatter class="org.openxava.formatters.MoneyFormatter" />
		<for-stereotype stereotype="DINERO" />
		<for-stereotype stereotype="MONEY" />
		<for-annotation annotation="org.openxava.annotations.Money"/> 
	</editor>
	
	<editor name="Email" url="textEditor.jsp">
		<property name="mask" value="*{1,50}[.*{1,50}][.*{1,50}][.*{1,50}][.*{1,50}]@*{1,30}[.*{1,12}][.*{1,2}]" />
        <for-stereotype stereotype="EMAIL"/>
        <for-annotation annotation="jakarta.validation.constraints.Email"/> 
        <for-annotation annotation="org.hibernate.validator.constraints.Email"/>     
    </editor>
    
    <editor name="EmailList" url="textEditor.jsp">
		<property name="mask" value="*{1,50}[.*{1,50}][.*{1,50}][.*{1,50}][.*{1,50}]@*{1,30}[.*{1,12}][.*{1,2}][, *{1,50}[.*{1,50}][.*{1,50}][.*{1,50}][.*{1,50}]@*{1,30}[.*{1,12}][.*{1,2}][, *{1,50}[.*{1,50}][.*{1,50}][.*{1,50}][.*{1,50}]@*{1,30}[.*{1,12}][.*{1,2}][, *{1,50}[.*{1,50}][.*{1,50}][.*{1,50}][.*{1,50}]@*{1,30}[.*{1,12}][.*{1,2}][, *{1,50}[.*{1,50}][.*{1,50}][.*{1,50}][.*{1,50}]@*{1,30}[.*{1,12}][.*{1,2}][, *{1,50}[.*{1,50}][.*{1,50}][.*{1,50}][.*{1,50}]@*{1,30}[.*{1,12}][.*{1,2}]]]]]]" />
        <for-stereotype stereotype="EMAIL_LIST"/>
        <for-stereotype stereotype="LISTA_EMAIL"/>
        <for-annotation annotation="org.openxava.annotations.EmailList"/>      
    </editor>
    
    <editor name="WebURL" url="webURLEditor.jsp">
    	<list-formatter class="org.openxava.formatters.WebURLFormatter"/>
        <for-stereotype stereotype="WEBURL"/>
        <for-annotation annotation="org.hibernate.validator.constraints.URL"/> 
    </editor>    
    
	<editor name="TextArea" url="textAreaEditor.jsp" frame="true">
		<for-stereotype stereotype="TEXTO_GRANDE" />
		<for-stereotype stereotype="MEMO" />
		<for-stereotype stereotype="TEXT_AREA" />
		<for-annotation annotation="org.openxava.annotations.TextArea"/> 
	</editor>

	<editor name="Label" url="labelEditor.jsp">
		<formatter from-type="true" />
		<for-stereotype stereotype="ETIQUETA" />
		<for-stereotype stereotype="LABEL" />
		<for-annotation annotation="org.openxava.annotations.Label"/> 
	</editor>

	<editor name="DateTimeCalendar" url="dateTimeCombinedCalendarEditor.jsp">
		<formatter class="org.openxava.formatters.DateTimeCombinedFormatter" />
		<for-type type="java.sql.Timestamp" />
		<for-stereotype stereotype="DATETIME" />
		<for-stereotype stereotype="FECHAHORA" />
		<for-annotation annotation="org.openxava.annotations.DateTime"/> 
	</editor>
	
	<editor name="DateTimeSeparatedCalendar" url="dateTimeSeparatedCalendarEditor.jsp">
		<formatter class="org.openxava.formatters.DateTimeSeparatedFormatter" />
	</editor>	
	
	<editor name="DateTimeCombinedCalendar" url="dateTimeCombinedCalendarEditor.jsp">
		<formatter class="org.openxava.formatters.DateTimeCombinedFormatter" />
	</editor>
	
	<editor name="BoldLabel" url="boldLabelEditor.jsp">
		<for-stereotype stereotype="ETIQUETA_NEGRITA" />
		<for-stereotype stereotype="BOLD_LABEL" />
	</editor>
	
	<editor name="Image" url="uploadEditor.jsp" format="false">
		<property name="loadAction" value="ImageEditor.load"/>
		<property name="removeAction" value="ImageEditor.remove"/>
		<property name="getURL" value="/xava/ximage"/>
		<property name="filesIdsProviderClass" value="org.openxava.web.editors.NullFilesIdsProvider"/>
		<property name="cssClass" value="ox-image"/>
		<property name="acceptFileTypes" value="image/*"/>  	
		<formatter class="org.openxava.formatters.ImageFormatter" />
		<for-stereotype stereotype="FOTO" />
		<for-stereotype stereotype="PHOTO" />
		<for-stereotype stereotype="IMAGEN" />
		<for-stereotype stereotype="IMAGE" />
	</editor>
	
	<editor name="Gallery" url="uploadEditor.jsp" format="false" frame="true">
		<property name="loadAction" value="GalleryEditor.load"/>
		<property name="removeAction" value="GalleryEditor.remove"/>
		<property name="getURL" value="/xava/gallery"/>
		<property name="filesIdsProviderClass" value="org.openxava.web.editors.ImagesGalleryFilesIdsProvider"/>
		<property name="multipleFiles" value="true"/> 
		<property name="cssClass" value="ox-gallery"/>
		<property name="acceptFileTypes" value="image/*"/>  
		<for-stereotype stereotype="IMAGES_GALLERY" />
		<for-stereotype stereotype="GALERIA_IMAGENES" />
	</editor>
	
	<editor name="FileItem" url="uploadEditor.jsp" format="false"> 
		<property name="loadAction" value="FileItemEditor.load"/> 
		<property name="removeAction" value="FileItemEditor.remove"/> 
		<property name="getURL" value="/xava/ximage"/> <!-- We should create a specific servlet for this, but for now it is not used for most cases -->
		<property name="filesIdsProviderClass" value="org.openxava.web.editors.NullFilesIdsProvider"/>
