=== openxava/openxava/Addons/xava/dtds/controladores.dtd
<!ELEMENT subcontrolador EMPTY>
<!ATTLIST subcontrolador
 controlador CDATA #REQUIRED
 imagen CDATA #IMPLIED
 icono CDATA #IMPLIED
 modo (detail|list|ALL|NONE) "ALL"
>

<!ELEMENT var-entorno EMPTY>
<!ATTLIST var-entorno
 nombre CDATA #REQUIRED
 valor CDATA #IMPLIED
>

<!ELEMENT objeto EMPTY>
<!ATTLIST objeto
 nombre CDATA #REQUIRED
 clase CDATA #REQUIRED
 valor CDATA #IMPLIED
 ambito (modulo|global) "modulo"
>

<!ELEMENT accion (poner*, usa-objeto*)>
<!ATTLIST accion
 nombre CDATA #REQUIRED
 etiqueta CDATA #IMPLIED
 descripcion CDATA #IMPLIED
 modo (detail|list|ALL|NONE) "ALL" 
 metodo CDATA #IMPLIED
 imagen CDATA #IMPLIED
 icono CDATA #IMPLIED
 atajo-de-teclado CDATA #IMPLIED
 clase CDATA #IMPLIED
 oculta (true|false) "false"
 al-iniciar (true|false) "false"
 en-cada-peticion (true|false) "false"
 antes-de-cada-peticion (true|false) "false"
 despues-de-cada-peticion (true|false) "false"
 por-defecto (nunca|casi-nunca|si-posible|casi-siempre|siempre) "casi-nunca"
 cuesta (true|false) "false" 
 confirmar (true|false) "false"
 en-cada-fila (true|false) "false"
 procesar-elementos-seleccionados (true|false) "false"
 disponible-en-nuevo (true|false) "true"
>

<!ELEMENT usa-objeto EMPTY>
<!ATTLIST usa-objeto
 nombre CDATA #REQUIRED
 propiedad-accion CDATA #IMPLIED
>

<!ELEMENT poner EMPTY>
<!ATTLIST poner
 propiedad CDATA #REQUIRED
 valor CDATA #REQUIRED
>

<!ELEMENT hereda-de EMPTY>
<!ATTLIST hereda-de
 controlador CDATA #REQUIRED
 acciones-excluidas CDATA #IMPLIED
>

<!ELEMENT controlador (hereda-de*, (accion|subcontrolador)*)>
<!ATTLIST controlador
 nombre CDATA #REQUIRED
 etiqueta CDATA #IMPLIED
 imagen CDATA #IMPLIED
 icono CDATA #IMPLIED
 clase CDATA #IMPLIED
 contexto (comun|swing|web) "comun"
>
<!ELEMENT controladores (var-entorno*, objeto*, controlador+)>

=== openxava/openxava/openxava-invoicing-archetype-spanish/src/main/resources/xava/controladores.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE controladores SYSTEM "dtds/controladores.dtd">

<!-- 
Documentación sobre controladores: 
https://www.openxava.org/OpenXavaDoc/docs/controllers_es.html

Controladores por defecto, incluidos en OpenXava (puedes extender de ellos):
https://github.com/openxava/openxava/blob/master/openxava/src/main/resources/xava/default-controllers.xml
 
Ejemplos de controladores (de la aplicación de pruebas):
https://github.com/openxava/openxava/blob/master/openxavatest/src/main/resources/xava/controllers.xml
-->

<controladores>
    
    <!-- Variable de entorno: 
    <var-entorno nombre="tuaplicacion_ANYO_DEFECTO" valor="2025"/>
    -->
    
    <!-- Objeto de sesión:
    <Objeto nombre="tuaplicacion_anyoActivo" clase="java.lang.Integer" valor="2025" 
            ambito="global"/>
    -->
    
    <!-- Controlador:
    <controlador nombre="Almacen">
        <hereda-de controlador="Typical"/>
        <accion nombre="new" icono="plus-box-multiple" atajo-de-teclado="Control N" 
                clase="com.tuempresa.tuaplicacion.acciones.CrearAlmacen"/>        
    </controlador>
    -->
    
	<!-- Para definir un valor global para una variable de entorno -->
	<var-entorno nombre="XAVA_SEARCH_ACTION"
		valor="Facturacion.buscarExcluyendoEliminados" />

	<controlador nombre="Facturacion"> <!-- El mismo nombre de la entidad -->

		<hereda-de controlador="Typical" /> <!-- Hereda todas las acciones de 'Typical' -->

		<!-- Typical ya tiene una acción 'delete', al usar el mismo nombre la sobrescribimos -->
		<accion nombre="delete" modo="detail" confirmar="true"
			clase="com.tuempresa.tuaplicacion.acciones.EliminarParaFacturacion"
			icono="delete" disponible-en-nuevo="false"
			atajo-de-teclado="Control D" />

		<accion nombre="buscarExcluyendoEliminados" oculta="true"
			clase="com.tuempresa.tuaplicacion.acciones.BuscarExcluyendoEliminados" />
		<!-- oculta="true" : Así la acción no se mostrará en la barra de botones -->

		<accion nombre="deleteSelected" modo="list" confirmar="true"
			procesar-elementos-seleccionados="true" icono="delete"
			clase="com.tuempresa.tuaplicacion.acciones.EliminarSeleccionadoParaFacturacion"
			atajo-de-teclado="Control D" />

		<accion nombre="deleteRow" modo="NONE" confirmar="true"
			clase="com.tuempresa.tuaplicacion.acciones.EliminarSeleccionadoParaFacturacion"
			icono="delete" en-cada-fila="true" />
	</controlador>



	<controlador nombre="Papelera">
		<accion nombre="restaurar" modo="list"
			clase="com.tuempresa.tuaplicacion.acciones.EliminarSeleccionadoParaFacturacion">
			<poner propiedad="restaurar" valor="true" /> <!-- Pone la propiedad restaurar a true -->
			<!-- antes de llamar al método execute() de la acción -->
		</accion>
	</controlador>


	<controlador nombre="Pedido">
		<hereda-de controlador="Facturacion" /> <!-- Para tener las acciones estándar -->

		<accion nombre="crearFactura" modo="detail"
			clase="com.tuempresa.tuaplicacion.acciones.CrearFacturaDesdePedido" />
		<!-- modo="detail" : Sólo en modo detalle -->

		<!-- La nueva acción -->
		<accion nombre="crearFacturaDesdePedidosSeleccionados"
			modo="list"
			clase="com.tuempresa.tuaplicacion.acciones.CrearFacturaDesdePedidosSeleccionados" />
		<!-- modo="list": Sólo se muestra en modo lista -->

		<accion nombre="buscarFactura"
			clase="com.tuempresa.tuaplicacion.acciones.BuscarFacturaDesdePedido"
			oculta="true" icono="magnify" />
		<!-- oculta="true" : Para que no se muestre en la barra de botones del 
			módulo icono="magnify" : La misma imagen que la de la acción estándar -->

	</controlador>


	<controlador nombre="EdicionFactura">

		<accion nombre="grabar"
			clase="com.tuempresa.tuaplicacion.acciones.GrabarFactura"
			atajo-de-teclado="Control S" />

		<accion nombre="cerrar"
			clase="org.openxava.actions.CancelAction" />

	</controlador>


	<controlador nombre="Factura">
		<hereda-de controlador="Facturacion" />

		<accion nombre="anyadirPedidos"
			clase="com.tuempresa.tuaplicacion.acciones.IrAnyadirPedidosAFactura"
			oculta="true" icono="table-row-plus-after" />
		<!-- oculta="true" : No se mostrará en la barra de botones del módulo icono="table-row-plus-after" 
			: La misma imagen que la acción estándar -->

	</controlador>

	<controlador nombre="AnyadirPedidosAFactura">
		<hereda-de controlador="AddToCollection" /> <!-- Extiende del controlador estándar -->

		<!-- Sobrescribe la acción para añadir -->
		<accion nombre="add"
			clase="com.tuempresa.tuaplicacion.acciones.AnyadirPedidosAFactura" />

	</controlador>    
    
</controladores>

=== openxava/openxava/openxava-project-management-archetype-spanish/src/main/resources/xava/controladores.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE controladores SYSTEM "dtds/controladores.dtd">

<!-- 
Documentación sobre controladores: 
https://www.openxava.org/OpenXavaDoc/docs/controllers_es.html

Controladores por defecto, incluidos en OpenXava (puedes extender de ellos):
https://github.com/openxava/openxava/blob/master/openxava/src/main/resources/xava/default-controllers.xml
 
Ejemplos de controladores (de la aplicación de pruebas):
https://github.com/openxava/openxava/blob/master/openxavatest/src/main/resources/xava/controllers.xml
-->

<controladores>
    
    <!-- Variable de entorno: 
    <var-entorno nombre="tuaplicacion_ANYO_DEFECTO" valor="2015"/>
    -->
    
    <!-- Objeto de sesión:
    <Objeto nombre="tuaplicacion_anyoActivo" clase="java.lang.Integer" valor="2015" 
            ambito="global"/>
    -->
    
    <!-- Controlador:
    <controlador nombre="Profesor">
        <hereda-de controlador="Typical"/>
        <accion nombre="new" icono="plus-box-multiple" atajo-de-teclado="Control N" 
                clase="acciones.CrearProfesor"/>        
    </controlador>
    -->
    
    <controlador nombre="IncidenciasVersion">
    	<accion nombre="new" oculta="true"
			icono="plus-box-multiple"
			clase="com.tuempresa.tuaplicacion.acciones.CrearNuevaIncidenciaEnVersion"/>
	</controlador>
    
    <controlador nombre="MiCalendario">
		<hereda-de controlador="CRUD"/>
		
		<accion nombre="new" 
			clase="com.tuempresa.tuaplicacion.acciones.CrearNuevaIncidenciaDesdeMiCalendario"
			imagen="new.gif"
			icono="plus-box-multiple"
			atajo-de-teclado="Control N"
			pierde-datos-cambiados="true">
			<poner propiedad="restoreModel" valor="true"/>						
		</accion>
		
		<accion nombre="save" modo="detail"
			por-defecto="si-posible"
			clase="com.tuempresa.tuaplicacion.acciones.GuardarVolviendoALista"
			imagen="save.gif"
			icono="content-save"
			atajo-de-teclado="Control S"/>
			
	</controlador>
    
</controladores>
