=== openxava/openxava/Addons/xava/dtds/editors.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT editors (editor*)>


<!ELEMENT editor (property*, formatter?, list-formatter?, (for-type | for-stereotype | for-model-property | for-valid-values | for-references | for-reference | for-collections | for-element-collections | for-collection | for-tabs | for-tab )*)>
<!ATTLIST editor
 name CDATA #IMPLIED
 url CDATA #REQUIRED
 format (true|false) "true" 
 depends-stereotypes CDATA #IMPLIED
 depends-properties CDATA #IMPLIED
 frame (true|false) "false"
 always-reload (true|false) "false"
 composite (true|false) "false" 
 icon CDATA #IMPLIED
 init-action CDATA #IMPLIED
 release-action CDATA #IMPLIED
 selectable-items (true|false) "true"
>

<!ELEMENT property EMPTY>
<!ATTLIST property
  name CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT formatter (set*)>
<!ATTLIST formatter
  class CDATA #IMPLIED
	from-type (true|false) "false"
>

<!ELEMENT list-formatter (set*)>
<!ATTLIST list-formatter
  class CDATA #IMPLIED
	from-type (true|false) "false"
>

<!ELEMENT set EMPTY>
<!ATTLIST set
 property CDATA #REQUIRED
 value CDATA #REQUIRED 
>

<!ELEMENT for-type EMPTY>
<!ATTLIST for-type
 type CDATA #REQUIRED
>

<!ELEMENT for-stereotype EMPTY>
<!ATTLIST for-stereotype
 stereotype CDATA #REQUIRED
>

<!ELEMENT for-model-property EMPTY>
<!ATTLIST for-model-property
 model CDATA #REQUIRED
 property CDATA #REQUIRED 
>

<!ELEMENT for-valid-values EMPTY>

<!ELEMENT for-references EMPTY>

<!ELEMENT for-reference EMPTY>
<!ATTLIST for-reference
 model CDATA #REQUIRED
>

<!ELEMENT for-collections EMPTY>

<!ELEMENT for-element-collections EMPTY>

<!ELEMENT for-collection EMPTY>
<!ATTLIST for-collection
 model CDATA #REQUIRED
>

<!ELEMENT for-tabs EMPTY>

<!ELEMENT for-tab EMPTY>
<!ATTLIST for-tab
 model CDATA #REQUIRED
>

=== openxava/openxava/Addons/xava/editors.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE editors SYSTEM "dtds/editors.dtd">

<!-- NaviOX -->

<editors>
	
	<editor url="textEditor.jsp">
		<for-model-property model="User" property="name" />		
		<for-model-property model="SignIn" property="user" />				
		<for-model-property model="Role" property="name" />
		<for-model-property model="Module" property="name" />		
		<for-model-property model="Module" property="application" />						
	</editor>
	
	<editor url="../../naviox/editors/actionsEditor.jsp" frame="true">			
		<formatter class="com.openxava.naviox.formatters.ArrayAsStringFormatter" />	
		<list-formatter class="com.openxava.naviox.formatters.ActionsListFormatter" />
		<for-model-property model="ModuleRights" property="excludedActions" />
	</editor>
	
	<editor url="../../naviox/editors/membersEditor.jsp" frame="true">			
		<formatter class="com.openxava.naviox.formatters.ArrayAsStringFormatter" />
		<list-formatter class="com.openxava.naviox.formatters.MembersListFormatter" />
		<for-model-property model="ModuleRights" property="excludedMembers" />
	</editor>
	
	<editor url="../../naviox/editors/membersEditor.jsp" frame="true">		
		<property name="excludeReadOnly" value="true"/>	
		<formatter class="com.openxava.naviox.formatters.ArrayAsStringFormatter" />
		<list-formatter class="com.openxava.naviox.formatters.MembersListFormatter" />
		<for-model-property model="ModuleRights" property="readOnlyMembers" /> 	
	</editor>

	<editor url="../../naviox/editors/organizationUrlEditor.jsp">
		<for-model-property model="Organization" property="url" />
	</editor>
	
	<editor url="textEditor.jsp">
		<list-formatter class="com.openxava.naviox.formatters.ThemeListFormatter"/>
		<for-model-property model="Organization" property="theme" />
	</editor>
	
	<editor url="../../naviox/editors/privacyPolicyEditor.jsp" frame="true">
		<for-model-property model="SignUp" property="privacyPolicy" />
	</editor>
	
	<editor url="textWithSuffixEditor.jsp">
		<property name="suffix" value="days_suffix"/>
		<for-model-property model="ConfigurationRecord" property="forceChangePasswordDays" />
	</editor>
	
	<editor url="textWithSuffixEditor.jsp">
		<property name="suffix" value="minutes_suffix"/>
		<for-model-property model="ConfigurationRecord" property="lockSessionMinutes" />
	</editor>
	
	<editor url="textWithSuffixEditor.jsp">
		<property name="suffix" value="days_suffix"/>
		<for-model-property model="ConfigurationRecord" property="inactiveDaysBeforeDisablingUser" />
	</editor>

	<editor url="textWithSuffixEditor.jsp">
		<property name="suffix" value="0_for_never_suffix"/>
		<for-model-property model="ConfigurationRecord" property="loginAttemptsBeforeLocking" />
	</editor>	
	
	<editor url="textWithSuffixEditor.jsp">
		<property name="suffix" value="days_suffix"/>
		<for-model-property model="ConfigurationRecord" property="inactiveDaysBeforeDisablingUser" />
	</editor>

	<editor url="booleanWithSuffixEditor.jsp">
		<property name="suffix" value="shared_users_change_warning"/>
		<formatter class="org.openxava.formatters.BooleanFormatter" >
			<set property="nullAsFalse" value="true"/>
		</formatter>
		<list-formatter class="org.openxava.formatters.BooleanListFormatter" />
		<for-model-property model="ConfigurationRecord" property="sharedUsersBetweenOrganizations" />
	</editor>
		
</editors>

=== openxava/openxava/OpenXavaTest/xava/editors.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE editors SYSTEM "dtds/editors.dtd">

<!-- OpenXavaTest -->

<editors>

	<editor name="GalleryNoDialog" url="galleryEditor.jsp">
		<property name="editAction" value="GalleryNoDialog.edit"/>
	</editor>

	<editor url="regionsEditor.jsp">
		<property name="regionsCount" value="3" />
		<formatter
			class="org.openxava.formatters.MultipleValuesByPassFormatter" />
		<for-stereotype stereotype="REGIONS" />
	</editor>

	<editor name="RegionsWithCheckBoxes" url="regionsWithCheckBoxesEditor.jsp">
		<property name="regionsCount" value="3" />
		<formatter
			class="org.openxava.formatters.MultipleValuesByPassFormatter" />
	</editor>
	
	<!-- For work only in uppercase -->
	<editor url="textEditor.jsp">
		<formatter class="org.openxava.formatters.UpperCaseFormatter" />
		<for-type type="java.lang.String" />
	</editor>

	<editor url="textEditor.jsp">
		<for-stereotype stereotype="NO_FORMATING_STRING" />
	</editor>
	
	<editor url="textEditor.jsp">
		<list-formatter class="org.openxava.formatters.HTMLFilterListFormatter" />
		<for-stereotype stereotype="NO_HTML_IN_LIST" />
	</editor>	
		
	<editor url="currentTimeMillisEditor.jsp" always-reload="true">
		<for-stereotype stereotype="CURRENT_TIME_MILLIS"/>
	</editor>

	<editor name="PersonName" url="textEditor.jsp">
		<formatter
			class="org.openxava.test.formatters.NameFormatter">
			<set property="firstLetterInUpperCase" value="true" />
		</formatter>
		<for-stereotype stereotype="PERSON_NAME" />
	</editor>
	
	<editor name="PlaceName" url="textEditor.jsp">
		<formatter
			class="org.openxava.test.formatters.NameFormatter">
			<set property="firstLetterInUpperCase" value="true" />
		</formatter>
	</editor>	
	
	<editor name="CityName" url="textEditor.jsp">
		<formatter
			class="org.openxava.test.formatters.NameFormatter">
			<set property="firstLetterInUpperCase" value="true" />
		</formatter>
		<list-formatter
			class="org.openxava.test.formatters.CityNameFormatter"/>		
		<for-stereotype stereotype="CITY_NAME" />
	</editor>	
	
	<editor url="corporationEmployeeListEditor.jsp">
		<for-tab model="CorporationEmployee"/>
	</editor>
		
	<editor name="CustomerCardList" url="customerCardListEditor.jsp"/>
		
	<editor url="colorEditor.jsp">
		<for-reference model="Color"/>
	</editor>
	
	<editor name="CarriersNames" url="carriersNamesEditor.jsp"/>
	
	<editor url="blogCommentsEditor.jsp">
		<for-collection model="BlogComment"/>
	</editor>
	
	<editor name="ColorFrame" url="colorFrameEditor.jsp" frame="true"/>
	
	<editor name="JbyXName" url="textEditor.jsp">
		<formatter
			class="org.openxava.test.formatters.JbyXNameFormatter">
			<set property="firstLetterInUpperCase" value="true" />
		</formatter>		
	</editor>
	 
	<editor url="textEditor.jsp">
		<for-model-property model="Product" property="unitPrice" />
	</editor>

	<editor url="descriptionsEditor.jsp">
		<property name="model" value="Family" />
		<property name="keyProperty" value="number" />
		<property name="descriptionProperty" value="description" />
		<property name="orderByKey" value="true" />
		<property name="readOnlyAsLabel" value="true" />
		<for-stereotype stereotype="FAMILY" />
	</editor>

	<!-- It is possible to specify dependencies from stereotypes or properties -->
	<editor url="descriptionsEditor.jsp" depends-stereotypes="FAMILY">
		<!--  
			<editor url="descriptionsEditor.jsp" depends-properties="familyNumber">
		-->
		<property name="model" value="Subfamily" />
		<property name="keyProperty" value="number" />
		<property name="descriptionProperties"
			value="number, description" />
		<property name="condition" value="${familyNumber} = ?" />
		<property name="parameterValuesStereotypes" value="FAMILY" />
		<!--
			<property name="parameterValuesProperties" value="familyNumber"/>
		-->
		<property name="descriptionsFormatter"
			value="org.openxava.test.formatters.FamilyDescriptionsFormatter" />
		<for-stereotype stereotype="SUBFAMILY" />
	</editor>

	<editor url="descriptionsEditor.jsp"
		depends-properties="family.number">
		<property name="model" value="Subfamily" />
		<property name="keyProperty" value="number" />
		<property name="descriptionProperties" value="description" />
		<property name="condition" value="${familyNumber} = ?" />
		<property name="parameterValuesProperties"
			value="family.number" />
		<for-stereotype stereotype="SUBFAMILY_DEPENDS_REFERENCE" />
	</editor>

	<editor url="descriptionsEditor.jsp" frame="true">
		<property name="model" value="Warehouse" />
		<property name="keyProperties" value="zoneNumber, number" />
		<property name="descriptionProperty" value="name" />
		<property name="filter"
			value="org.openxava.test.filters.LimitZoneFilter" />
		<property name="condition" value="${zoneNumber} &lt;= ?" />
		<formatter
			class="org.openxava.test.formatters.WarehouseFormatter" />
		<for-stereotype stereotype="WAREHOUSE" />
	</editor>

	<editor url="descriptionsEditor.jsp">
		<property name="model" value="Delivery" />
		<property name="keyProperties"
			value="invoice.year, invoice.number, type.number, number" />
		<property name="descriptionProperty" value="description" />
		<for-stereotype stereotype="DELIVERIES" />
	</editor>

	<editor url="descriptionsEditor.jsp"
		depends-properties="family, detail.subfamily">
		<property name="model" value="ServiceType" />
		<property name="keyProperty" value="number" />
		<property name="descriptionProperty" value="description" />
		<property name="condition"
			value="${family} = ? and ${subfamily} = ?" />
		<property name="parameterValuesProperties"
			value="family, detail.subfamily" />
		<for-stereotype stereotype="SERVICE_TYPE" />
	</editor>

	<editor url="descriptionsEditor.jsp" depends-properties="oid" >
		<property name="model" value="Product3" />
		<property name="keyProperty" value="number" />
		<property name="descriptionProperty" value="description" />
		<property name="condition" value="${family.oid} = ?" />
		<property name="parameterValuesProperties" value="oid" />
		<for-stereotype stereotype="PRODUCT3" />
	</editor>
	
	<editor url="descriptionsEditor.jsp" depends-properties="familyList">
		<property name="model" value="Product2" />
		<property name="keyProperty" value="number" />
		<property name="descriptionProperty" value="description" />
		<property name="condition" value="${family.number} = ?" />
		<property name="parameterValuesProperties" value="this.familyList" />
		<for-stereotype stereotype="PRODUCT2" />
	</editor>	

	<editor url="descriptionsEditor.jsp">
		<property name="model" value="Customer.Receptionist" />
		<property name="keyProperty" value="oid" />
		<property name="descriptionProperty" value="name" />
		<for-stereotype stereotype="RECEPTIONIST" />
	</editor>

	<editor name="UserAttribute" url="userAttributeEditor.jsp"/>

	<editor name="TreeViewAlternate" url="treeViewEditor.jsp">
		<property name="reader" value="org.openxava.test.web.editors.impl.TreeViewReaderTestImpl" />
	</editor>
	
	<editor name="Important" url="importantEditor.jsp"/>
	
	<editor name="CustomWebURL" url="customWebURLEditor.jsp">
    	<list-formatter class="org.openxava.formatters.WebURLFormatter"/>
    </editor>
    
    <editor name="CarColor" url="validValuesEditor.jsp">
    	<list-formatter class="org.openxava.test.formatters.CarColorFormatter"/>
	</editor>
	
</editors>
