=== openxava/openxava/chatvoice/src/main/resources/xava/dtds/aplicacion.dtd
<!ELEMENT aplicacion (modulo-defecto?, modulo*)>
<!ATTLIST aplicacion
 nombre ID #REQUIRED
 etiqueta CDATA #IMPLIED
>

<!ELEMENT modulo-defecto (controlador*)>

<!ELEMENT modulo (doc | (var-entorno*, modelo?, vista?, vista-swing?, vista-web?, tab?, controlador*, controlador-modo?) | listado)>
<!ATTLIST modulo
 nombre ID #REQUIRED
 carpeta CDATA #IMPLIED
 etiqueta CDATA #IMPLIED
 descripcion CDATA #IMPLIED
>

<!ELEMENT doc EMPTY>
<!ATTLIST doc
 url CDATA #REQUIRED
 idiomas CDATA #IMPLIED
>

<!ELEMENT var-entorno EMPTY>
<!ATTLIST var-entorno
 nombre CDATA #REQUIRED
 valor CDATA #IMPLIED
>


<!ELEMENT modelo EMPTY>
<!ATTLIST modelo
 nombre CDATA #REQUIRED
>

<!ELEMENT vista EMPTY>
<!ATTLIST vista
 nombre CDATA #REQUIRED
>

<!ELEMENT tab EMPTY>
<!ATTLIST tab
 nombre CDATA #REQUIRED
>


<!ELEMENT vista-swing EMPTY>
<!ATTLIST vista-swing
 clase CDATA #REQUIRED
>

<!ELEMENT vista-web EMPTY>
<!ATTLIST vista-web
 url CDATA #REQUIRED
>



<!ELEMENT controlador EMPTY>
<!ATTLIST controlador
 nombre CDATA #REQUIRED
>

<!ELEMENT controlador-modo EMPTY>
<!ATTLIST controlador-modo
 nombre CDATA #REQUIRED
>



<!ELEMENT listado EMPTY>
<!ATTLIST listado
 modelo CDATA #REQUIRED
 tab CDATA #IMPLIED
>

=== openxava/openxava/openxava-invoicing-archetype-spanish/src/main/resources/xava/aplicacion.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?><!DOCTYPE aplicacion SYSTEM "dtds/aplicacion.dtd"><aplicacion nombre="tuaplicacion"> 		<!--	Un módulo por defecto se asume para cada	controlador en <modulo-defecto/> 	-->	<modulo-defecto>		  		<controlador nombre="Typical"/>			</modulo-defecto>		<!--	Podemos definir módulos adicionales, por ejemplo: 		<modulo nombre="ClienteSoloLectura">		<modelo nombre="Cliente"/>		<controlador nombre="Print"/>	</modulo>			-->	  		<modulo nombre="PapeleraFactura">        <var-entorno nombre="XAVA_LIST_ACTION"        valor="Papelera.restaurar"/> <!-- La acción a mostrar en cada fila -->        <modelo nombre="Factura"/>        <tab nombre="Eliminado"/> <!-- Para mostrar solo las entidades borradas -->        <controlador nombre="Papelera"/> <!-- Con solo una acción: restaurar -->    </modulo>     <modulo nombre="PapeleraPedido">        <var-entorno nombre="XAVA_LIST_ACTION"         valor="Papelera.restaurar"/>        <modelo nombre="Pedido"/>        <tab nombre="Eliminado"/>        <controlador nombre="Papelera"/>    </modulo>			</aplicacion>
