=== openxava/openxava/chatvoice/src/main/resources/xava/dtds/application.dtd
<!ELEMENT application (default-module?, module*)>
<!ATTLIST application
 name ID #REQUIRED
 label CDATA #IMPLIED
>

<!ELEMENT default-module (controller*)>

<!ELEMENT module (doc | (env-var*, model?, view?, web-view?, tab?, controller*, mode-controller?))>
<!ATTLIST module
 name ID #REQUIRED
 folder CDATA #IMPLIED
 label CDATA #IMPLIED
 description CDATA #IMPLIED
>

<!ELEMENT doc EMPTY>
<!ATTLIST doc
 url CDATA #REQUIRED
 languages CDATA #IMPLIED
>

<!ELEMENT env-var EMPTY>
<!ATTLIST env-var
 name CDATA #REQUIRED
 value CDATA #IMPLIED
>


<!ELEMENT model EMPTY>
<!ATTLIST model
 name CDATA #REQUIRED
>

<!ELEMENT view EMPTY>
<!ATTLIST view
 name CDATA #REQUIRED
>

<!ELEMENT tab EMPTY>
<!ATTLIST tab
 name CDATA #REQUIRED
>


<!ELEMENT web-view EMPTY>
<!ATTLIST web-view
 url CDATA #REQUIRED
>



<!ELEMENT controller EMPTY>
<!ATTLIST controller
 name CDATA #REQUIRED
>

<!ELEMENT mode-controller EMPTY>
<!ATTLIST mode-controller
 name CDATA #REQUIRED
>

=== openxava/openxava/openxava-invoicing-archetype/src/main/resources/xava/application.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?><!DOCTYPE application SYSTEM "dtds/application.dtd"><application name="yourapp"> 		<!-- 	A default module for each entity is assumed with the	controllers on <default-module/>	-->	<default-module>		  		<controller name="Typical"/>			</default-module>		<!-- 	You can define additional modules, for example:	  	<module name="OnlyReadTeacher">		<model name="Teacher"/>		<controller name="Print"/>	</module>			-->		<module name="InvoiceTrash">		<env-var name="XAVA_LIST_ACTION" value="Trash.restore" /> <!-- The action to be shown in each row -->		<model name="Invoice" />		<tab name="Deleted" /> <!-- To show only the deleted entities -->		<controller name="Trash" /> <!-- With only one action: restore -->	</module>	<module name="OrderTrash">		<env-var name="XAVA_LIST_ACTION" value="Trash.restore" />		<model name="Order" />		<tab name="Deleted" />		<controller name="Trash" />	</module>		</application>

=== openxava/openxava/chatvoice/src/main/resources/xava/application.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE application SYSTEM "dtds/application.dtd">

<application name="chatvoice"> 
	
	<!-- 
	A default module for each entity is assumed with the
	controllers on <default-module/>
	-->
	<default-module>		  
		<controller name="Typical"/>		
	</default-module>
	
	<!-- 
	You can define additional modules, for example:	  
	<module name="OnlyReadTeacher">
		<model name="Teacher"/>
		<controller name="Print"/>
	</module>		
	-->
	
	<module name="Dashboard">
		<model name="Dashboard"/>
		<controller name="InitModelWithNewInstance"/>
	</module>
	
	<module name="Chat">
		<model name="Chat"/>
		<controller name="InitModelWithNewInstance"/>
		<controller name="Chat"/>
	</module>
	
</application>
