=== openxava/openxava/chatvoice/src/main/resources/xava/dtds/controllers.dtd
<!ELEMENT subcontroller EMPTY>
<!ATTLIST subcontroller
 controller CDATA #REQUIRED
 image CDATA #IMPLIED
 icon CDATA #IMPLIED
 mode (detail|list|ALL|NONE) "ALL"
>

<!ELEMENT env-var EMPTY>
<!ATTLIST env-var
 name CDATA #REQUIRED
 value CDATA #IMPLIED
>

<!ELEMENT object EMPTY>
<!ATTLIST object
 name CDATA #REQUIRED
 class CDATA #REQUIRED
 value CDATA #IMPLIED
 scope (module|global) "module"
>

<!ELEMENT action (set*, use-object*)>
<!ATTLIST action
 name CDATA #REQUIRED
 label CDATA #IMPLIED
 description CDATA #IMPLIED
 mode (detail|list|ALL|NONE) "ALL"
 image CDATA #IMPLIED
 icon CDATA #IMPLIED
 keystroke CDATA #IMPLIED
 class CDATA #REQUIRED
 hidden (true|false) "false"
 on-init (true|false) "false"
 on-each-request (true|false) "false"
 before-each-request (true|false) "false"
 after-each-request (true|false) "false"
 by-default (never|almost-never|if-possible|almost-always|always) "almost-never"
 takes-long (true|false) "false"
 confirm (true|false) "false"
 in-each-row (true|false) "false"
 process-selected-items (true|false) "false"
 available-on-new (true|false) "true"
 loses-changed-data (true|false) "false"
>

<!ELEMENT use-object EMPTY>
<!ATTLIST use-object
 name CDATA #REQUIRED
 action-property CDATA #IMPLIED
>

<!ELEMENT set EMPTY>
<!ATTLIST set
 property CDATA #REQUIRED
 value CDATA #REQUIRED
>

<!ELEMENT extends EMPTY>
<!ATTLIST extends
 controller CDATA #REQUIRED
 excluded-actions CDATA #IMPLIED
>

<!ELEMENT controller (extends*, (action|subcontroller)*)>
<!ATTLIST controller
 name CDATA #REQUIRED
 label CDATA #IMPLIED
 image CDATA #IMPLIED
 icon CDATA #IMPLIED
>
<!ELEMENT controllers (env-var*, object*, controller*)>

=== openxava/openxava/openxava-invoicing-archetype/src/main/resources/xava/controllers.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE controllers SYSTEM "dtds/controllers.dtd">

<!-- 
Controllers doc: 
https://www.openxava.org/OpenXavaDoc/docs/controllers_en.html

Default controllers included in OpenXava (you can extend from them):
https://github.com/openxava/openxava/blob/master/openxava/src/main/resources/xava/default-controllers.xml
 
Examples of controllers (from test application):
https://github.com/openxava/openxava/blob/master/openxavatest/src/main/resources/xava/controllers.xml
-->

<controllers>
    
    <!-- Environment variable:
    <env-var name="yourapp_DEFAULT_YEAR" value="2025"/> 
    -->
    
    <!-- Session object:
    <object name="yourapp_activeYear" class="java.lang.Integer" value="2025" 
    	    scope="global"/>    
    -->
    
    <!-- Controller:
    <controller name="Warehouse">
    	<extends controller="Typical"/>
    	<action name="new" icon="plus-box-multiple" keystroke="Control N"
        	class="com.yourcompany.yourapp.actions.CreateWarehouseAction">
    	</action>
	</controller>    
    -->
    
	<env-var name="XAVA_SEARCH_ACTION"
		value="Invoicing.searchExcludingDeleted" />
	<controller name="Invoicing"> 

		<extends controller="Typical" /> <!-- It has all the actions from Typical -->

		<!-- Typical already has a 'delete' action, by using the same name we override it -->
		<action name="delete" mode="detail" confirm="true"
			class="com.yourcompany.yourapp.actions.InvoicingDeleteAction"
			icon="delete" available-on-new="false" keystroke="Control D" />

		<action name="searchExcludingDeleted" hidden="true"
			class="com.yourcompany.yourapp.actions.SearchExcludingDeletedAction" />

		<action name="deleteSelected" mode="list" confirm="true"
			process-selected-items="true" icon="delete"
			class="com.yourcompany.yourapp.actions.InvoicingDeleteSelectedAction"
			keystroke="Control D" />

		<action name="deleteRow" mode="NONE" confirm="true"
			class="com.yourcompany.yourapp.actions.InvoicingDeleteSelectedAction"
			icon="delete" in-each-row="true" />

	</controller>


	<controller name="Trash">
		<action name="restore" mode="list"
			class="com.yourcompany.yourapp.actions.InvoicingDeleteSelectedAction">
			<set property="restore" value="true" /> <!-- Initialize the restore property to -->
			<!-- true before calling the execute() method of the action -->
		</action>
	</controller>


	<controller name="Order">
		<extends controller="Invoicing" /> <!-- In order to have the standard actions -->

		<action name="createInvoice" mode="detail"
			class="com.yourcompany.yourapp.actions.CreateInvoiceFromOrderAction" />
		<!-- mode="detail" : Only in detail mode -->

		<!-- The new action -->
		<action name="createInvoiceFromSelectedOrders" mode="list"
			class="com.yourcompany.yourapp.actions.CreateInvoiceFromSelectedOrdersAction" />
		<!-- mode="list": Only shown in list mode -->

		<action name="searchInvoice"
			class="com.yourcompany.yourapp.actions.SearchInvoiceFromOrderAction"
			hidden="true" icon="magnify" />
		<!-- hidden="true" : Because we don't want the action to be shown in module 
			button bar icon="magnify" : The same icon as for the standard search action -->
	</controller>


	<controller name="InvoiceEdition">

		<action name="save"
			class="com.yourcompany.yourapp.actions.SaveInvoiceAction"
			keystroke="Control S" />

		<action name="close" class="org.openxava.actions.CancelAction" />

	</controller>


	<controller name="Invoice">
		<extends controller="Invoicing" />

		<action name="addOrders"
			class="com.yourcompany.yourapp.actions.GoAddOrdersToInvoiceAction"
			hidden="true" icon="table-row-plus-after" />
		<!-- hidden="true" : Because we don't want the action to be shown in module 
			button bar icon="table-row-plus-after" : The same icon as for the standard 
			action -->

	</controller>

	<controller name="AddOrdersToInvoice">
		<extends controller="AddToCollection" /> <!-- Extends from the standard controller -->

		<!-- Overwrites the action to add -->
		<action name="add"
			class="com.yourcompany.yourapp.actions.AddOrdersToInvoiceAction" />

	</controller>    
    
</controllers>

=== openxava/openxava/Addons/xava/controllers.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE controllers SYSTEM "dtds/controllers.dtd">

<!-- NaviOX -->

<controllers>

	<object name="naviox_locked" class="java.lang.Boolean" value="false" scope="global"/>
	<object name="naviox_locking" class="java.lang.Boolean" value="false"/>

	<controller name="SignIn">
	
		<action name="init" on-init="true" hidden="true"  			
			class="com.openxava.naviox.actions.InitSignInAction"/>
	
		<action name="signIn"  			
			class="com.openxava.naviox.actions.SignInAction"/>			
					
	</controller>
	
	<controller name="GoSignUp">
		
		<action name="signUp"
        	class="com.openxava.naviox.actions.GoSignUpAction"/>	
        	
	</controller>
	
	<controller name="UserJoin">
		
        <action name="join"
        	class="com.openxava.naviox.actions.UserJoinAction"/>	
        	
	</controller>	
	
	<controller name="SignUp">
    	<action name="init" on-init="true" hidden="true"
        	class="com.openxava.naviox.actions.InitSignUpAction"/>		
    	<action name="signUp" takes-long="true"
        	class="com.openxava.naviox.actions.SignUpAction"/>							      
	</controller>
	
	<controller name="RecoverPassword">
    	<action name="recoverPassword"
        	class="com.openxava.naviox.actions.RecoverPasswordAction"/>			
	</controller>
	
	<controller name="RestorePassword">
		<action name="init" on-each-request="true" hidden="true"
			class="com.openxava.naviox.actions.InitRestorePasswordAction"/>
    	<action name="setPassword"
        	class="com.openxava.naviox.actions.RestorePasswordAction"/>        					      	
	</controller>	

	<controller name="SessionLocker">
		<action name="lock" hidden="true" 			
			class="com.openxava.naviox.actions.LockAction"/>
		<action name="unlock" hidden="true" 			
			class="com.openxava.naviox.actions.UnlockAction"/>
	</controller>
	
	<controller name="Configuration">
	
		<action name="init" after-each-request="true" hidden="true"  			
			class="com.openxava.naviox.actions.InitConfigurationAction"/>
	
		<action name="save" mode="detail"
			by-default="if-possible"
			class="com.openxava.naviox.actions.SaveConfigurationAction"
			keystroke="Control S"/>
						
	</controller>		
	
	<controller name="History">
		<extends controller="Print"/>
		<action name="warnNotEnabled" on-init="true" hidden="true" 
			class="com.openxava.naviox.actions.WarnHistoryNotEnabledAction"/> 
	</controller>

	<controller name="User">
		<extends controller="Typical"/>
		<action name="init" after-each-request="true" hidden="true"
        	class="com.openxava.naviox.actions.InitUserAction"/>
		<action name="save" mode="detail"
			by-default="if-possible"
			class="com.openxava.naviox.actions.SaveUserAction"
			image="save.gif"
			icon="content-save"
			keystroke="Control S"/>	
	</controller>
	
	<controller name="Module">
		<extends controller="Navigation"/>
		<extends controller="Print"/>
		<action name="save" mode="detail"
			by-default="if-possible"
			class="org.openxava.actions.SaveAction"
			image="save.gif"
			icon="content-save"
			keystroke="Control S"/>
			
		<action name="refresh" mode="detail"			
			class="org.openxava.actions.SearchAction"
			image="refresh.gif"
			icon="refresh"
			keystroke="control B"/>			
	</controller>
	
	<controller name="Role">
		<extends controller="Typical"/>
		<action name="addModulesRights" icon="table-row-plus-after" hidden="true"
			class="com.openxava.naviox.actions.GoAddModulesRightsToRoleAction"/>										
	</controller>
	
	<controller name="AddToModulesRights">
		<extends controller="AddToCollection"/>
		<action name="add" 
			class="com.openxava.naviox.actions.AddModulesRightsToRoleAction"/>		
	</controller>
	
	
	<controller name="Folder">
		<extends controller="Typical"/>
		
		<action name="updateROOTFolder" hidden="true" on-init="true" 
			class="com.openxava.naviox.actions.UpdateROOTFolderAction"/>		
		<action name="saveSubfolder" hidden="true" 
			class="com.openxava.naviox.actions.SaveSubfolderAction"/>
	</controller>
	
	<controller name="ChangePassword">
		<action name="init" after-each-request="true"  hidden="true"  			
			class="com.openxava.naviox.actions.InitChangePasswordAction"/>
		<action name="changePassword" 
			class="com.openxava.naviox.actions.ChangePasswordAction"/>			
	</controller>
	
	<controller name="MyPersonalData">
		<action name="init" on-init="true"  hidden="true"  			
			class="com.openxava.naviox.actions.InitMyPersonalDataAction"/>
		<action name="save" 
			class="com.openxava.naviox.actions.SaveMyPersonalDataAction"/>			
	</controller>
	
	<controller name="WarnNoEmail">
		<action name="warnNoEmail" after-each-request="true" hidden="true"
			class="com.openxava.naviox.actions.WarnNoEmailAction"/>
	</controller>
	
	<controller name="NewOnlyInList">
		<action  name="new" mode="list"
			class="org.openxava.actions.NewAction"
			icon="library-plus"
			keystroke="Control N">
			<set property="restoreModel" value="true"/>			
		</action>
	</controller>
	
	<controller name="Organization">
		<extends controller="Navigation"/>
		<extends controller="NewOnlyInList"/>
		<extends controller="Print"/>
		
		<action name="init" hidden="true" on-init="true"
			class="com.openxava.naviox.actions.InitOrganizationAction"/>	
				
		<action name="createNewOrganization" mode="detail" takes-long="true"
			class="com.openxava.naviox.actions.CreateNewOrganizationAction"/>
			
		<action name="modify" mode="detail" available-on-new="false"
			class="com.openxava.naviox.actions.ModifyOrganizationAction"
			by-default="if-possible"
			keystroke="F3">			
			<set property="resetAfter" value="false"/>
		</action>			
			
		<action name="delete" mode="detail" confirm="true"
			class="com.openxava.naviox.actions.DeleteOrganizationAction"/>
		
		<action name="go" in-each-row="true" mode="NONE" icon="exit-to-app"			
			class="com.openxava.naviox.actions.GoOrganizationAction"/>
						
	</controller>

	<controller name="PhoneList">

		<action name="orderByAscending" 
			class="com.openxava.phone.actions.OrderByAscendingAction"/>
			
		<action name="orderByDescending" 
			class="com.openxava.phone.actions.OrderByDescendingAction"/>	
		
	</controller>
		
</controllers>

=== openxava/openxava/openxava-project-management-archetype/src/main/resources/xava/controllers.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE controllers SYSTEM "dtds/controllers.dtd">

<!-- 
Controllers doc: 
https://www.openxava.org/OpenXavaDoc/docs/controllers_en.html

Default controllers included in OpenXava (you can extend from them):
https://github.com/openxava/openxava/blob/master/openxava/src/main/resources/xava/default-controllers.xml
 
Examples of controllers (from test application):
https://github.com/openxava/openxava/blob/master/openxavatest/src/main/resources/xava/controllers.xml
-->

<controllers>
    
    <!-- Environment variable:
    <env-var name="yourapp_DEFAULT_YEAR" value="2015"/> 
    -->
    
    <!-- Session object:
    <object name="yourapp_activeYear" class="java.lang.Integer" value="2015" 
    	    scope="global"/>    
    -->
    
    <!-- Controller:
    <controller name="Teacher">
    	<extends controller="Typical"/>
    	<action name="new" icon="library-plus" keystroke="Control N"
        	class="actions.CreateTeacher">
    	</action>
	</controller>    
    -->
    
    <controller name="VersionIssues">
    	<action name="new" hidden="true"
			icon="library-plus"
			class="com.yourcompany.yourapp.actions.CreateNewIssueInVersionAction"/>
	</controller>
	
	<controller name="MyCalendar">
		<extends controller="CRUD"/>
		
		<action name="new" 
			class="com.yourcompany.yourapp.actions.NewIssueFromMyCalendarAction"
			image="new.gif"
			icon="library-plus"
			keystroke="Control N"
			loses-changed-data="true">
			<set property="restoreModel" value="true"/>						
		</action>
		
		<action name="save" mode="detail"
			by-default="if-possible"
			class="com.yourcompany.yourapp.actions.SaveReturningToListAction"
			image="save.gif"
			icon="content-save"
			keystroke="Control S"/>
			
	</controller>
    
</controllers>
